name: story_video_player
description: Video player for Flutter similar to Instagram reels or Tiktok.
version: 1.0.0
homepage: https://github.com/TobiasPrt/story_video_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.0.0
  flutter_cache_manager: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1


flutter:

